name: Security CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: platform-zero/.github/.github/workflows/security-ci.yml@8690aa7cbdccaa74d3a84ccf8073678e8bc811de
